name: 'tech_graveyard_dbt'
version: '1.0.0'
config-version: 2

flags:
  send_anonymous_usage_stats: False
  
# This profile name MUST match the one in profiles.yml
profile: 'tech_graveyard_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Define how models in different folders should be materialized
models:
  tech_graveyard_dbt:
    staging:
      materialized: view
    marts:
      materialized: table